# Setup
title:            RogueBit
tagline:          'My Cloud Portfolio'
description:      'RogueBit Realm: Your cybersecurity sharpshooter and trusty cloud guide staking your claim in the digital frontier.'
url:              https://0xeb0din.github.io
baseurl:          ''
paginate:         5
github:
  repo: https://github.com/0xeb0din
personal:
  url: https://roguebit.me/

# About and contact
author:
  name:           'RogueBit'
  url:            https://twitter.com/0xeb0din

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version: 3.0.0