# Setup
title:            RogueBit
tagline:          'My Cloud Portfolio'
description:      'Venturing beyond AWS to the vast landscape of cloud providers, "RogueBit Realm" focuses on budget-friendly, secure tech solutions for the savvy cloud explorer.'
url:              https://0xeb0din.github.io
baseurl:          ''
paginate:         5
github:
  repo: https://github.com/0xeb0din

# About and contact
author:
  name:           'RogueBit'
  url:            https://twitter.com/0xeb0din

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version: 3.0.0