# Setup
title:            RogueBit
tagline:          'My Cloud Portfolio'
description:      'Building my cloud portfolio here <a href="https://jekyllrb.com" target="_blank">Jekyll</a> kill me now. Made by <a href="https://twitter.com/0xeb0din" target="_blank">@0xeb0din</a>.'
url:              https://roguebit.me
baseurl:          ''
paginate:         5
github:
  repo: https://github.com/0xeb0din

# About and contact
author:
  name:           'RogueBit'
  url:            https://twitter.com/0xeb0din

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
