# Setup
title:            RogueBit
tagline:          'My Cloud Portfolio'
description:      'RogueBit Realm: Your compass in the cloud and cybersecurity universe. Discover cost-effective, secure cloud solutions and master the art of digital defense. We''re not just exploring cloud technology; we''re fortifying it against the ever-evolving threats of the cyber world.'
url:              https://0xeb0din.github.io
baseurl:          ''
paginate:         5
github:
  repo: https://github.com/0xeb0din
personal:
  url: https://roguebit.me/

# About and contact
author:
  name:           'RogueBit'
  url:            https://twitter.com/0xeb0din

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version: 3.0.0